---
title: "Welcome to data science in R for the NBA"
description: |
  For all things data science, NBA and analytics 
author:
  - name: Guy Frederick Sutton
    url: 
    affiliation: 
    affiliation_url: 
date: 01-23-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

I have always been an avid sports fanatic - growing up as a kid in South Africa, sport is just a way of life. Rugby, cricket, football (soccer), golf, tennis, you name it... As I got older, my attention shifted to American football (NFL) and baseball. More recently, I have become a massive NBA fan - who can say no to a massive Jarrett Allen block, or a Giannis dunk? 

This blog will serve as a space for me to combine my love for basketball and data analytics/data science that I have developed over the course of getting a PhD in the sciences. I have about 8 years of experience using the `R` statistical platform, which has become one of the most popular statistics programmes worldwide. Most of my work will thus be written in `R`, however, I hope to add to my data analysis skills by learning some new languages and skills (e.g. `Julia` and `SQL`). 

